CREATE TABLE IF NOT EXISTS numbers (
    ADD Moeda VARCHAR(50) NOT NULL,
    ADD Periodicidade TIME NOT NULL,
    ADD Date_time DATETIME NOT NULL,
    ADD Open DECIMAL NOT NULL,
    ADD Low DECIMAL NOT NULL,
    ADD High DECIMAL NOT NULL,
    ADD Close DECIMAL NOT NULL
);
